insert into subjects values ( 'BMATS101',
                              'Mathematics-I For CSE Stream',
                              'CSE',
                              1,
                              4,
                              '*ASC(IC)' );
insert into subjects values ( 'BCHES102',
                              'Chemistry for CSE Stream',
                              'CSE',
                              1,
                              4,
                              '#ASC(IC)' );
insert into subjects values ( 'BCEDK103',
                              'Computer Aided Engineering Drawing',
                              'CSE',
                              1,
                              3,
                              'ESC' );
insert into subjects values ( 'BESCK104A',
                              'Introduction to Civil Engineering',
                              'CSE',
                              1,
                              3,
                              'ESC-II' );
insert into subjects values ( 'BPLCK105A',
                              'Introduction to Web Programming',
                              'CSE',
                              1,
                              3,
                              'ETC-II' );
insert into subjects values ( 'BENGK106',
                              'Communicative English',
                              'CSE',
                              1,
                              1,
                              'AEC' );
insert into subjects values ( 'BKSKK107',
                              'Samskrutika Kannada',
                              'CSE',
                              1,
                              1,
                              'HSMC' );
insert into subjects values ( 'BIDTK158',
                              'Innovation And Design Thinking',
                              'CSE',
                              1,
                              1,
                              'SDC' );

insert into subjects values ( 'BCS301',
                              'Mathematics for CSE Stream',
                              'CSE',
                              3,
                              4,
                              'BSC' );
insert into subjects values ( 'BCS302',
                              'Digital Design and Computer Organization',
                              'CSE',
                              3,
                              4,
                              'PCC' );
insert into subjects values ( 'BCS303',
                              'Operating System',
                              'CSE',
                              3,
                              4,
                              'PCC' );
insert into subjects values ( 'BCS304',
                              'Data Structures and Application',
                              'CSE',
                              3,
                              3,
                              'PCC' );
insert into subjects values ( 'BCSL305',
                              'Data Structures Lab',
                              'CSE',
                              3,
                              1,
                              'PCCL' );
insert into subjects values ( 'BCS306A',
                              'Objects Oriented Programming with JAVA',
                              'CSE',
                              3,
                              3,
                              'IPCC' );
insert into subjects values ( 'BCS307',
                              'Social Connect and Responsibility',
                              'CSE',
                              3,
                              1,
                              'AEC' );
insert into subjects values ( 'BCS358B',
                              'R Programming',
                              'CSE',
                              3,
                              1,
                              'AEC' );
insert into subjects values ( 'BNSK359',
                              'National Service Scheme',
                              'CSE',
                              3,
                              0,
                              'MC' );

insert into subjects values ( 'BCS401',
                              'Analysis & Design of Algorithms',
                              'CSE',
                              4,
                              3,
                              'PCC' );
insert into subjects values ( 'BCS402',
                              'Microcontrollers',
                              'CSE',
                              4,
                              4,
                              'IPCC' );
insert into subjects values ( 'BCS403',
                              'Database Management Systems',
                              'CSE',
                              4,
                              4,
                              'IPCC' );
insert into subjects values ( 'BCSL404',
                              'Analysis & Design of Algorithms Lab',
                              'CSE',
                              4,
                              1,
                              'PCCL' );
insert into subjects values ( 'BCS405B',
                              'Grapgh Theorey',
                              'CSE',
                              4,
                              3,
                              'ESC' );
insert into subjects values ( 'BCSL407',
                              'Biology for Computer Engineers',
                              'CSE',
                              4,
                              2,
                              'BSC' );
insert into subjects values ( 'BUHK408',
                              'Universal Human Values Course',
                              'CSE',
                              4,
                              1,
                              'UHV' );
insert into subjects values ( 'BCSL456D',
                              'Technical Writing using LATEX',
                              'CSE',
                              4,
                              1,
                              'AEC' );
insert into subjects values ( 'BNSK459',
                              'National Service Scheme',
                              'CSE',
                              4,
                              0,
                              'MC' );